### ISSUE TITLE
Enter key behavior in chat composites

### ISSUE THREAD

**Issue by Maki0301** [Azure/communication-ui-library#1425]
When I type a chat message, I press the Enter key to confirm the conversion in Japanese input, but if I do that in Chrome and Safari on the Mac, the message is sent.
In Japanese input, I have to press Enter several times to confirm the conversion, but I'm hoping that the Enter key after confirmation will send the message.
In Windows, it works as expected.

**Comment by dmceachernmsft** [comment]
Hi Maki! I was hoping to get some clarification into your issue. When you talk about 'confirming the conversion' are you referring to a software keyboard typing in Japanese? I was also wondering which platforms you were encountering this issue? it isn't immediately clear which browser is giving you trouble.

**Comment by Maki0301** [comment]
Thank you.
It seems to me that software keyboard refers to a virtual keyboard that is displayed on the PC screen, or does it refer to Japanese input?
 I am sorry I don't know the exact English, but it is the keyboard we use everyday to input Japanese.

I consider it to be the same thing as described on this site (https://blog.utgw.net/entry/2021/06/29/212256).

I tested this on a MacBook Pro (macOS Big Sur) with Safari (version 15.0) and Chrome (version 98.0.4758.80) browsers.

I took a video of me typing in Japanese, so I've attached it for your reference.
[](url

https://user-images.githubusercontent.com/29361769/153378654-2e7fc062-df15-4c08-92ec-2dad30de8042.mp4

)

**Comment by dmceachernmsft** [comment]
Thank you for the video! From what I am seeing here is that you are finished typing words in your tool and pressing enter to put them in the message bar but is sending the message before it is completed?

**Comment by dmceachernmsft** [comment]
https://user-images.githubusercontent.com/94866715/153497331-d958d446-b290-4ba1-ad86-dca9aea61304.mp4

Hi Maki, attached is a video on how to see the different events coming from the input box. the steps are as follows:

1. in the sample chat app or story book open up your dev tools
2. select the pick a element tool in the top corner
3. with your mouse select your input bar
4. open the console in the browser tools
5. use the command `monitorEvents($0)` -> this monitors the events on the last selected element.

once you start typing in the box it will tell you all the events that are being emitted from the input box. This might be useful to you so you can monitor to see if the input box is still receiving events even when your software tool is the program in focus and should be trapping them. 

Hope this helps you understand the issue and please do send us a link to the tool you are using so we can investigate into if there is something that we can do on our end!

**Comment by Maki0301** [comment]
If we add the following in the component code, it will do what we want it to do.
InputBoxComponent.tsx
```
const` onTexFieldKeyDown = useCallback(
    (ev: React.KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      //added--------------------------------------------------------
      if((ev.nativeEvent as any).isComposing || ev.keyCode===229){
        return;
      }
      //--------------------------------------------------------------
      if (ev.key === 'Enter' && (ev.shiftKey === false || !supportNewline)) {
        ev.preventDefault();
        onEnterKeyDown && onEnterKeyDown();
      }
      onKeyDown && onKeyDown(ev);
    },
    [onEnterKeyDown, onKeyDown, supportNewline]
  );
```

 However, "keyCode" is deprecated.

**Comment by dmceachernmsft** [comment]
Thanks for the code snippet Maki, looking into what this does I discovered that on mac this isn't just an issue for you but this is a known issue on mac for a few other languages as well! I will look into adding this and seeing about the deprecated use of keycode. Will keep you updated when this is fixed!

**Comment by Maki0301** [comment]
Thank you for your support.
if ((ev.nativeEvent as KeyboardEvent).isComposing) {
        return;
}
This code gave us the behavior we wanted in Chrome on Mac.
However, it did not give us the expected behavior in Safari on Mac.

**Comment by dmceachernmsft** [comment]
Thanks for letting me know Maki! WIll double check on our end that the behavior on safari is correct and let you know what we find! 

Thank you again for raising the issue and pointing us to the isComposing prop on the keyboard events! we've passed the findings off to fluent so that hopefully this wont be a issue on other input boxes in other apps in the future. So thank you very much for your insight here Maki!

**Comment by dmceachernmsft** [comment]
Hi Maki I apologize I didn't follow up with this sooner! Some digging has revealed that Apple does not play nice with React. Safari unfortunately does not support the event type InputEvent, something that React fires for all of its events which are wrapped up as synthetic events. Since this is not supported by Apple and Safari this is something we don't have a good fix for. 

We will be looking into adding a solution using the deprecated keycode property but we are looking to do it in such a way it does not break anything when the property finally leaves the browser event properties. Thank you again for your insight into the isComposing property and raising this issue with us! Hopefully Apple gets around to supporting that event type and we can provide you with a more complete solution.
