### ISSUE TITLE
Admission failed when Teams meeting has a lobby feature

### ISSUE THREAD

**Issue by m-muratori** [Azure/communication-ui-library#1713]
**Describe the bug; what happened?**
On some devices (es. Huawei P9 Lite Android 9, Nexus 7 Android 6) when a user is admitted from the lobby the ACS client is automatically disconneted from the Teams meeting. If the meeting has the lobby disabled the user is admitted without problems. 

**What are the steps to reproduce the issue?**
1. The guest user access the lobby
2. The meeting host admits the guest user
3. The meeting hosted is notified the the admission is failed
4. The guest user disconnects

**What behavior did you expect?**
The users should correctly be admitted to the meeting

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

- OS & Device: Huawei P9 Lite
- Browser Google Chrome
- Version: Android 9

- OS & Device: Nexus 7
- Browser: Google Chrome
- Version: Android 6

**Is there any additional information?**

**Comment by prabhjot-msft** [comment]
@m-muratori could you please provide the Google Chrome version that is being used, there was a related bug which was fixed for 96+ versions.

**Comment by m-muratori** [comment]
Hi @prabhjot-msft, here the Chrome versions:
Nexus 7 - Chrome 96.0.4664.104
Huawei P9 Lite - Chrome 99.0.4844.73

**Comment by prprabhu-ms** [comment]
Hi @m-muratori,

Thanks for filing the detailed issue and providing version info. The issue is unexpected in the browser versions you mentioned. 
It'll help to get the call Id of a call that fails in this manner. Could you help reproduce this and grab the call Id?

Are you using one of our sample apps? If so, the callId is noted in the console log when the sample starts. If the issue occurs in your own application, one way to get the callId is by enabling verbose logging in the SDK, as described at https://www.npmjs.com/package/@azure/logger

![image](https://user-images.githubusercontent.com/82062616/160498069-a18dd1c5-979f-4295-9e0d-93b32451fb42.png)

(But set it to `'debug'`).
That makes the console logging quite chatty, but you can grab the call Id from there.

In the meantime, I'll also try to reproduce this on my end.

**Comment by m-muratori** [comment]
Hi @prprabhu-ms,

this should be the CallId: **b056023a-acb7-4c5c-abed-84c7e530ba97**

And these are the errors I get:

![image](https://user-images.githubusercontent.com/26094189/160571119-e3c62818-bf0f-4220-bf21-7af21c377eaf.png)

**Comment by prprabhu-ms** [comment]
Thanks a lot @m-muratori for helping me debug this issue.

I was able to get server-side logs with the callId you provided. I'm looking at this some more today and will get back to you soon.

**Comment by prprabhu-ms** [comment]
Update. I was able to get server-side logs for callId `b056023a-acb7-4c5c-abed-84c7e530ba97` . But from the server-side logs I see that only the Nexus 7 had a failed connect in that call. The error on Nexus 7 is expected -- there is a known issue in Chrome M96 and earlier that can cause this failure mode. The Azure Communication Services Calling SDK only supports the last 3 versions of Chrome (So M99 -> M97), and the bug is in Chrome itself, so it's unlikely to be fixed for Nexus 7.

Did you also see the error on Huawei P99 Lite in that call? It'd be great to get a repro on that device (M99) and get client side logs as well as the callId.

Again, thank you very much for helping me debug this issue by reproducing and getting logs. Hopefully we can get to the bottom of this soon.

**Comment by m-muratori** [comment]
Hi @prprabhu-ms thanks for you time, I tried with the development team to reproduce the issue with the Hauwei P9 Lite and Chrome 99.0.4844.73 but surprisingly we were not able to reproduce the issue. Everything seems to work fine now, we were correctly admitted to the meeting.
