### ISSUE TITLE
Customize location of date time in chat messages

### ISSUE THREAD

**Issue by sangeethav123** [Azure/communication-ui-library#1905]
By using cross-platform - Chat composite js bundle file (Azure communication services the UI Library) for chat, we are looking to have own customization on the alignment for the date & time element.

For Example, I need the date and time to be at the bottom of every messages and on with Right Align for the sent message and the left Align for the received messages like below Image,
![Expected date and time style](https://user-images.githubusercontent.com/97170459/169063411-5fe83603-034e-43d6-8b5b-fcd498a824b1.PNG)

I have already tried to achieve using this link,
https://azure.github.io/communication-ui-library/?path=/docs/ui-components-messagethread--message-thread

But on some cases, it is not working as expected because the CSS classes are dynamically generated. So writing our own CSS for customization will not be suitable.

**Comment by mgamis-msft** [comment]
Hi @sangeethav123, thanks for filing this issue. I will do some investigation on whether customization is enough to achieve what you showed above or if a feature request is needed.

**Comment by mgamis-msft** [comment]
Hi @sangeethav123, I just want to confirm if you were able to achieve the image above using the `onRenderMessage` prop of `MessageThread`. Could you give some example code that did not work in some case because CSS classes are dynamically generated? I created a repo where I used the `onRenderMessage` prop which you can try on your side [here](https://github.com/mgamis-msft/chat-with-custom-message-rendering/blob/main/src/ChatComponentsStateful.tsx#L53). Let me know if something like this would work?

**Comment by mgamis-msft** [comment]
> Hi, I have attached the screenshots below: ![code for message container customization](https://user-images.githubusercontent.com/97170459/169855241-9f284c73-517c-47c8-8a8a-b180114cba19.PNG)
> 
> I have written customized CSS code using class “.bi .ui-chat__messageheader” to make the date and time format to be right aligned for sent messages like below: ![working customization css code](https://user-images.githubusercontent.com/97170459/169857399-253833a0-d704-4ccb-bf2b-a1177e135db5.PNG)
> 
> On some cases, the class names were different (dynamically created classes) and not working as expected, ![not working customization css](https://user-images.githubusercontent.com/97170459/169858406-435aadcd-de89-4d74-b912-ffe74e25012a.PNG)

Hi @sangeethav123, I am not sure why the `text-align: right` is not being applied in some cases. Just looking at the screenshot of code you provided and I think there should be more code that extract `messageProps.message.createdOn` property to put it in some div outside the chat bubble. Do you have a `defaultOnRender` callback that handles this logic? There should be some logic that also uses the dynamic `messageProps.messageContainerStyle` you assigned there. I hope I am making sense :). 

Also If I may suggest using a Stack from fluent-ui so that you can assign alignment easily like in my sample code on this [line](https://github.com/mgamis-msft/chat-with-custom-message-rendering/blob/main/src/ChatComponentsStateful.tsx#L24)

**Comment by sangeethav123** [comment]
Hi,

In the code screenshot for onRenderMessages, we have used messageProps.messageContainerStyle to modify the message container text color and background color. There we cannot apply **text-align: right** because it will make the **entire message** to be on **right alignment**.

We need only the date to be right aligned for message that we have sent(messageProps.message.mine) so we try to override it by using CSS classes. In that case, I have used the class which is highlighted in screenshot  (ui-flex ao bi bj) to make the date right aligned. Since, the CSS class names are dynamically generated we can't able to override it.

And also. we have already discussed we are using **chat composite js bundle(non-react)** and followed the below link(custom message sample code) to override CSS,
https://azure.github.io/communication-ui-library/?path=/docs/ui-components-messagethread--message-thread
I think so we cannot use Stack from fluent-ui(react). Correct me if I'm wrong!

**Comment by prabhjot-msft** [comment]
Hi @sangeethav123, sorry for the confusion about this issue. Normally, the date is rendered in message bubble when the `onRenderMessage` prop of `MessageThread` is not used and looks like below.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/97124699/170593924-c1006229-4904-4e4d-ab33-1a95bc6fa63f.png)
We wanted to know how you were able to move the date of the message outside the message bubble.

**Comment by sangeethav123** [comment]
Hi,
We use CSS to move the date of the message outside the message bubble. I have attached screenshot below
![date bubble css](https://user-images.githubusercontent.com/97170459/170687176-3d351774-5a02-4acf-866d-596cf9626008.PNG)

**Comment by mgamis-msft** [comment]
Hi @sangeethav, I think I understand the issue now. The dynamic CSS classes are provided by @fluentui/react-northstar a library we depend on for components to create our MessageThread component. So adding CSS styles to target class names of MessageThread elements will not work consistently.

I want start by saying we don't recommend using styling only to change the way messages look since it is difficult and usually "hacky." But if you want to proceed, I tried modifying your onRenderMessage callback below so that it will style the div around the timestamps consistently. Please give it a try.
```
const onRenderMessage = (messageProps, defaultOnRender) => {
  messageProps.showDate = true;
  if (messageProps.message.mine) {
    messageProps.messageContainerStyle = {
      backgroundColor: '#007994',
      color: '#FFFFFF !important',
      borderRadies: '8px !important',
      right: 0,
      '& .ui-chat__messageheader': {
        position: 'absolute',
        bottom: '-22px',
        right: 0
      }
    }
  } else {
    messageProps.messageContainerStyle = {
      broderRadius: '8px important',
      left: 0,
      '& .ui-chat__messageheader': {
        position: 'absolute',
        bottom: '-22px',
        left: 0
      }
    }
  }
  return defaultOnRender ? defaultOnRender(messageProps) : '';
}
```

We highly recommend you use Typescript and use our typescript quickstarts from here https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-composites--page. This is because the `onRenderMessage` prop is highly typed and was intended for components to be written.

But if you are only using js, you should still be able to write React components like `Stack` from fluent-ui with jsx files but you would have to change your webpack config to do so.

**Comment by sangeethav123** [comment]
Hi,
I have followed your code for onRenderMessages callback and its working fine now.
Thanks!
