### ISSUE TITLE
Unable to create/initiate callComposite 

### ISSUE THREAD

**Issue by nmaredia** [Azure/communication-ui-library#2397]
**Describe the bug; what happened?**
I was trying to create callComposite and chatComposite by following [this ](https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-composites--page) quickstart guide 

**What are the steps to reproduce the issue?**
1- Copied the code provided in tutorial. 
2- added my ID, Token and ACS resource url. 
3- Run `npm run start`

**What behavior did you expect?**
I expect it to run the same way shown in the quick start

**If applicable, provide screenshots:**
console log:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/75100936/195219305-2544f6f6-cb6d-4343-a5cf-179777d27826.png)

**In what environment did you see the issue?**

    "@azure/communication-calling": "^1.4.4",
    "@azure/communication-chat": "^1.2.0",
    "@azure/communication-react": "^1.3.1",

- OS & Device: [Windows] 
- Browser: [Google Chrome]
- Browser Version: [Version 106.0.5249.103 (Official Build) (64-bit)]

**Comment by PorterNan** [comment]
Disccussed offline with @nmaredia about the problem, it is caused by incompatible react version (React 18), and the incompatible react version cause the re-render of the whole page when throwing error, which creates duplicated callAgent.
Since we are going to update our quick start page, adding more details of React version, this will be not an issue, please expect the next update of our storybook with next beta release soon
