### ISSUE TITLE
ChatComposite load history messages

### ISSUE THREAD

**Issue by haohighview** [Azure/communication-ui-library#2760]
I'm using
https://azure.github.io/communication-ui-library/?path=/docs/composites-chat-basicexample--basic-example

Now I want to load history messages when "ChatComposite" is initialized. I try to call “adapter.loadPreviousChatMessages”, it doesn't work.

- `@azure/communication-react` npm package version (if applicable): [e.g. 1.5.0]
- `@azure/communication-calling` npm package version (if applicable): [e.g. 1.10.0-beta.1]
- `@azure/communication-chat` npm package version (if applicable): [e.g. 1.3.0]

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser: [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
- Browser Version: [e.g. 1.8.0]

**Comment by JamesBurnside** [comment]
Hi @haohighview, thanks for reporting the issue. To help further I had a couple of questions/asks:
* What is the issue you are seeing - are no chat messages loading, or are some chat messages loading but less than you expect?
* Could you post any error messages you see in the developer console
* Can you post a code snippet for how you are creating the adapter, where you are calling `adapter.loadPreviousChatMessages(<number of messages>)` and how this adapter is passed into the chat composite?
* Could you post the chat thread Id, loading previous messages is limited in TeamsInterop scenarios.

**Comment by haohighview** [comment]
I am using the above code return "loaded messages true", but the chat list is empty.
temas threadId 
19%3Ameeting_ODM2YTlkYjctNjk0MS00NDU3LWE1MjUtYzk5MmQ3ZDI1ZmM4%40thread.v2.

Every time you exit the meeting, an error will be triggered.
![image](https://user-images.githubusercontent.com/8456671/220513842-0c36102f-635f-4b08-afc3-a116f73a8520.png)

**Comment by JamesBurnside** [comment]
The threadId above is for a Teams interop meeting. Unfortunately there is limited ability to see the chat of a Teams interop meeting.

To be able to access the chat the user must first be accepted into the meeting - this is typically achieved by first having the user join the meeting as a guest via a call. Otherwise any call to chat APIs will be denied as the user is denied permission to access the chat.
Secondly, if the user is accepted into a call, that user can only access chat history from the time they are accepted into the meeting going forward - they cannot get any chat history/past messages before that datetime.

Can you confirm if your user either:
a) has not been accepted into the meeting and is therefore denied access to the chat
or 
b) has been accepted into the meeting and simply there are no older messages to load since the time they were accepted into the meeting
?

**Comment by haohighview** [comment]
> The threadId above is for a Teams interop meeting. Unfortunately there is limited ability to see the chat of a Teams interop meeting.
> 
> To be able to access the chat the user must first be accepted into the meeting - this is typically achieved by first having the user join the meeting as a guest via a call. Otherwise any call to chat APIs will be denied as the user is denied permission to access the chat. Secondly, if the user is accepted into a call, that user can only access chat history from the time they are accepted into the meeting going forward - they cannot get any chat history/past messages before that datetime.
> 
> Can you confirm if your user either: a) has not been accepted into the meeting and is therefore denied access to the chat or b) has been accepted into the meeting and simply there are no older messages to load since the time they were accepted into the meeting ?

has been accepted into the meeting.
Users can send messages, but cannot load previous messages. 

https://user-images.githubusercontent.com/8456671/220513842-0c36102f-635f-4b08-afc3-a116f73a8520.png
403 is triggered every time you exit the meeting.

**Comment by JamesBurnside** [comment]
Hi @haohighview, could you confirm what messages you are expecting the message thread to show that you are unable to see?
Note that users that have been accepted to a meeting can only see chat messages from that point onwards. If you subsequently send any messages in that teams meeting can the user see those messages correctly?

Regarding the 403 permission denied error, thank you for bringing this to our attention. After looking into it, the error is unrelated and is fired because of some internal logic trying to fetch the last message of a user that was just removed from the meeting. We have a fix (https://github.com/Azure/communication-ui-library/pull/2777 ) for it up now but should not be impacting the loadPreviousMessages issue you are seeing.

**Comment by haohighview** [comment]
Sent messages can be seen by users. 
>Note that users that have been accepted to a meeting can only see chat messages from that point onwards
It is currently not possible to load historical messages.

I have no other questions, thanks！
