### ISSUE TITLE
Can i add a sample app to repo?

### ISSUE THREAD

**Issue by netscout** [Azure/communication-ui-library#3140]
I made a sample group call client, server using @azure/communication-react@1.5.1-beta.5 which is support react 18.
I have searched simple group call samples but samples in this repo are little bit complex.
So I made a sample repo [acs-group-call-react-sample](https://github.com/netscout/acs-group-call-react-sample).

![image](https://github.com/Azure/communication-ui-library/assets/1797407/dfd071da-6ef7-4f3c-99b8-ec5eaacaeb1c)

used these tech stack:
- [Node.js](https://nodejs.org/en/download/) version 18
- [React](https://reactjs.org/) 18.2
- express, ts-node, typescript, tailwindcss
- [@azure/communication-react](https://www.npmjs.com/package/@azure/communication-react/v/1.5.1-beta.5) 1.5.1-beta.5 (the latest version that support react 18 as of 2023-06-02)

if it's okay i want to add my sample to this repo. 😊

It's my first time suggest something to opensource project, so i don't know it's a good place to write this and how to do it.
Let me know if i can do something. 😊

Thank you!

**Comment by alkwa-msft** [comment]
Greetings @netscout 

Thanks for sharing this github issue. It took us some time to discuss with the team about how we want to handle this situation. 

Today we recognize our "samples" directory is quite heavy and we are most likely going to rename it to "sandbox" or "playground" since it is designed for us to evaluate our packlets in the UI Library.

As for a simpler sample, we have a separate repository just to have a sample around a calling experience using the CallComposite. https://github.com/Azure-Samples/communication-services-web-calling-hero
We invite you to check it out if you want an easier to digest sample calling UI experience.

As for taking in your suggested sample we need to evaluate the maintenance and our vision for how we are building out the UI Library. Since we already have a more "sample" at the repo, it would be challenging for us to support everyone's sample.

That being said we did have a discussion and it would be an awesome idea to share a small list of interesting projects that use the UI Library and we would like to link to your repo if you would be interested. We will work on additional community guidelines but at this time we would love to start this process and highlight your project if you would be interested.

**Comment by netscout** [comment]
Thanks for considering my suggestion! 😄
