### ISSUE TITLE
We are facing "display name" issue using createAzureCommunicationCallAdapter

### ISSUE THREAD

**Issue by NaisargiGitHub** [Azure/communication-ui-library#3890]
We are using the callback function createAzureCommunicationCallAdapter to initiate the call. But we are facing issue.

Please find the video for the issue - 
[DisplayName 2023-12-06.zip](https://github.com/Azure/communication-ui-library/files/13614233/DisplayName.2023-12-06.zip)

Do give us a quick solution. 

Thanks in advance.

**Comment by NaisargiGitHub** [comment]
We have passed **displayName** to createAzureCommunicationCallAdapter, but we are getting below error:-

![img_20231214](https://github.com/Azure/communication-ui-library/assets/147044641/956c0fa1-f462-402f-9c3a-8c8a87bed54b)

**Comment by JamesBurnside** [comment]
If your participant's identity is a Teams user, you must use createTeamsCallAdapter instead of createAzureCommunicationCallAdapter.
In which case you won't pass a display name, but if you have multiple clients joining via azure communication services, you will need to use `onFetchProfile` to ensure other they have displayNames pulled form EntraId. Per this [documentation](https://azure.github.io/communication-ui-library/?path=/docs/communicationasteamsuser--page#using-ui-library-in-communication-as-teams-user-scenarios).
Note that support for joining calls with a Teams identity is in [Public Preview](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/)

**Comment by NaisargiGitHub** [comment]
Is there any workaround from which we can resolve "**Display Name Issue**" using **createAzureCommunicationCallAdapter.** ?

The solution provided by you is very time-consuming and needs to rewrite most of the things. So if possible can you provide some quick and short solutions?

**Comment by alkwa-msft** [comment]
A few issues here.

If you are trying to join a call using a teams token and using the actual teams identity, you need to use the createTeamsCallAdapter. This is not negotiable.

For calls where you are using a Teams identity, it was deemed a security issue to set your name via the displayName similar to a normal ACS call. You can imagine that I could just set my display name and display picture to what you may have and tell everyone I am giving out free pizza at my desk. 

We do allow this type of change on the UI layer but it is only for the client side and does not persist to the other users.  This is what James has posted above and is currently the only way to set display names for calls where you are using a Teams identity today. Since this doesn't change your display name for other people in the call, my example around free pizza would not work.

If this feature request is critical for your scenario then please follow up and we can see how can we best be able to support you.

**Comment by dmceachernmsft** [comment]
Closing as old issue. please reopen if related questions arise
