### ISSUE TITLE
"video-tile-display-name" is hard to see if user's background is white in Dark Theme and vice versa

### ISSUE THREAD

**Issue by lovedota** [Azure/communication-ui-library#4644]
HI Team

I am using

```
"@azure/communication-calling": "^1.24.3",
"@azure/communication-common": "^2.3.1",
"@azure/communication-identity": "^1.3.1",
"@azure/communication-react": "^1.16.0",
import { FluentThemeProvider, lightTheme, darkTheme } from '@azure/communication-react';

```

We figure out the `video-tile-display-name` is not dynamic with the user's background and it becomes hard to see.

![Wisory_Video_2_0](https://github.com/Azure/communication-ui-library/assets/417914/67334923-134e-48de-9873-7420c22d764e)

**Comment by mgamis-msft** [comment]
Hi @lovedota, am I correct in assuming you are using components and you are using the darkTheme for your `FluentThemeProvider` because of the import statement you provided?
I wonder if you could debug/console.log the value of property `callingPalette.videoTileLabelBackgroundLight` of the fluentTheme object you are passing to `FluentThemeProvider`. The value for darkTheme should be `rgba(37,36,35,0.8)` as defined in our [themes file](https://github.com/Azure/communication-ui-library/blob/main/packages/react-components/src/theming/themes.ts#L103).
So the display name background should be a dark grey color instead of the light grey color I am seeing in the image you provided.

**Comment by lovedota** [comment]
Hi @mgamis-msft 

When the camera is turned off, we can see the display name easily, but when it is turned on it is a problem

![Wisory_Video_2_0](https://github.com/Azure/communication-ui-library/assets/417914/aeb15195-c354-48ad-87dd-fdc864ed3f43)

**Comment by mgamis-msft** [comment]
Hi @lovedota, I'm not sure why this is happening because I tried reproducing this in our CallWithChatComposite 
with version "@azure/communication-react": "^1.16.0" and see the displayName background remain the same when video is on or off.
Are you using the CallWithChatComposite? If so, could you show all properties you assigning?

**Comment by lovedota** [comment]
Solved cc @mgamis-msft 
My issue is about
I am using this tool https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html to generate the new theme.
The generated code is not contains this one
```
callingPalette: {
    videoTileLabelBackgroundLight: 'rgba(37,36,35,0.8)'
}
```
I copied this one from `darkTheme` and it works
