### ISSUE TITLE
How to integrate adapter with communication-monitoring

### ISSUE THREAD

**Issue by lovedota** [Azure/communication-ui-library#5312]
Hi Team

How to integrate with https://github.com/Azure/communication-monitoring 
In the guidelines, it requires CallAgent and CallClient to be integrated

```
import { CallAgent, CallClient } from '@azure/communication-calling'
import { CommunicationMonitoring } from 'communication-monitoring'

interface Options {
  callClient: CallClient
  callAgent: CallAgent
  divElement: HTMLDivElement
}

const selectedDiv = document.getElementById('selectedDiv')

const options = {
  callClient = this.callClient,
  callAgent = this.callAgent,
  divElement = selectedDiv,
}

const communicationMonitoring = new CommunicationMonitoring(options)
```

In the real use case, we use adapter for the video app, how can we integrate with communication monitoring 
```
const adapter = useAzureCommunicationCallWithChatAdapter(
    {
      userId,
      displayName,
      credential,
      endpoint,
      locator,
      /* @conditional-compile-remove(video-background-effects) */ callAdapterOptions: callAdapterOptions
    },
    afterAdapterCreate
  );
```

**Comment by mgamis-msft** [comment]
Hi @lovedota, thank you for filing this issue. We are looking into this.

**Comment by mgamis-msft** [comment]
@lovedota I'm afraid he adapters were not designed to work with https://github.com/Azure/communication-monitoring because we don't expose the call client and call agent when the adapter hook `useAzureCommunicationCallWithChatAdapter` is used to create the CallWithChatAdapter, We create them internally.
I would suggest to use the stateful implementation of video calling app like this [quickstart](https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-starting-with-calling-stateful) to have access to the call client and call agent as parameters for creating `CommunicationMonitoring`. 
Could that be an alternative?

**Comment by lovedota** [comment]
HI
I am finding a solution to detect if our participants are having errors and sending a signal to our servers to warn our admin. Could it be done by other way or we need the communication monitoring

**Comment by mgamis-msft** [comment]
From the discussion with my team, we don't recommend using https://github.com/Azure/communication-monitoring because we had issues using it and it has not been updated in 2 years.

We also discussed other solutions for you to detect participant errors. You can detect call and chat errors as well as specific diagnostic events by subscribing to events on your CallWithChatAdapter like shown in this code snippet:
```
  import { DiagnosticQuality } from '@azure/communication-calling';
  
  ...

  const afterAdapterCreate = useCallback(async (adapter: CallWithChatAdapter): Promise<CallWithChatAdapter> => {
    adapter.on('callError', (e) => {
      console.log('Sending call error event to admin:', e);
    });
    adapter.on('chatError', (e) => {
      console.log('Sending chat error event to admin:', e);
    });
    adapter.onStateChange((state: CallWithChatAdapterState) => {
      if (
        state.call?.diagnostics.media.latest.cameraFreeze?.value === DiagnosticQuality.Bad ||
        state.call?.diagnostics.media.latest.cameraFreeze?.value === DiagnosticQuality.Poor
      ) {
        console.log('Camera freeze detected. Sending to admin with with call info: ', state.call);
      } else if (
        state.call?.diagnostics.network.latest.networkSendQuality?.value === DiagnosticQuality.Bad ||
        state.call?.diagnostics.network.latest.networkSendQuality?.value === DiagnosticQuality.Poor
      ) {
        console.log('Bad network send quality detected. Sending to admin with call info: ', state.call);
      } ...
    });
    return adapter;
  }, []);

  const adapter = useAzureCommunicationCallWithChatAdapter(
    {
      userId,
      displayName,
      credential,
      endpoint,
      locator,
      alternateCallerId,
      callAdapterOptions: callAdapterOptions
    },
    afterAdapterCreate
  );
```
For more information on all the diagnostic events, you can check this [documentation](https://learn.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/user-facing-diagnostics). There is also [media quality stats](https://learn.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/media-quality-sdk?pivots=platform-web) from @azure/communication-calling, but we have not implemented in our state yet.

Would something like this work for you?

We are also talking with @azure/communication-calling, if they will have any tooling available for error detection..

**Comment by dmceachernmsft** [comment]
Closing issue as last response is more than 10 days old. please reopen the issue if you have further questions on the topic
